config/routes.rb
Wikiful::Application.routes.draw do
  

  get "welcome/index"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "articles/index"
  get "categories/index"

  root 'welcome#index'
  resources :articles
  resources :categories
  resources :users
  resources :sessions

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :article_categories # <= this was accidentally :articles
	has_many :categories, through: :article_categories  #<= this was :articles_categories  ... extra 'S' in there
	validates :title, presence: true
	validates :content, presence: true
	validates :categories, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article 
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
    has_many :articles, through: :article_categories
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	has_many :articles
	validates_uniqueness_of :email
	validates :name, presence: true
	validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :get_categories

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  private
  def get_categories
  	@categories = Category.all.order(:name)
  end

  def authorize
  	redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authorize, only: [:new, :edit, :update]
  
  def index
  	@articles = Article.order(updated_at: :desc).limit(25)
  end
  
  def show
  	@article = Article.find(params[:id])
  end

  def new

  	@article = Article.new
  end

  def create

  	@article = Article.new(article_params)
  	if @article.save
  		redirect_to @article
  	else
  		render "new"
  	end
  end

  private
     def article_params

     	params.require(:article).permit(:title, :content, :category_ids => [])
     end

  	  	
end

app/controllers/articles_controllers.rb
class ArticlesController < ApplicationController
  def index
  end
  
  def show
  end

  def new
  end

  def create
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all.order(:name)
  end
  
  def show
  	@category = Category.find(params[:id])
  end
  	  	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to root_url, notice: "Logged in"
  	else
  		flash.now.alert = "Email or password is invalid"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out"
  end
  
  private
  def current_user
  	@current_user ||= User.find(sessions[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url, notice: "Thank you for signing up"
		else
			render "new"
		end
	end

	private
	def user_params
		params.require(:user).permit(:email, :name, :password, :password_confirmation)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    skip_before_filter :get_categories
    layout 'welcome'
    
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1> This is the first view  for the articles </h1>

<% @articles.each do |article| %>
  <div>
    <h3><%= link_to article.title, article %></h3>
  	<p>Published on <%= article.created_at.strftime('%b %d, %Y') %></p>
    <p>Filed under: <% article.categories.each do |category| %>
                      <%= category.name %>&nbsp;
                    <% end %>
    </p>
    <p><%= truncate(article.content, length: 200) %></p>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1> Write and publish a New Article</h1>

<% if @article.errors.any? %>

	<div class = "error_message">
		<h2>You're missing some fields</h2>
		<ul>
			<% @article.errors.full_messages do |message| %>
			<li><%= message %></li>
			<% end %>
				
		</ul>
		
	</div>
<% end %>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<div>
  <h1><%= @article.title %></h1>
  <p>Published <%= @article.created_at.strftime('%b %d, %Y') %></p>
  <p>Filed under: <% @article.categories.each do |category| %>
    <%= category.name %>&nbsp;<% end %>
  </p>
  <div><%= @article.content %></div>
</div>

app/views/articles/show.index.erb
show.html.erb

app/views/categories/index.html.erb
<h1>Wiki Categories</h1>

<h3> Ckick on any link below to see articles tagged with the category</h3>

<ul>
	<% @categories.each do |category| %>

	<h4>
		<%= link_to category.name, category %>
	</h4>

	<% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<h3>There are <%= @category.articles.count %> articles filed under <%= @category.name %></h3>

<ul>
	<% @category.articles.order(:title).each do |article| %>

	<h4>
		<%= link_to article.title, article %>
	</h4>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikiful- What Do You Want To Learn Today?</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
</head>
<body>

	<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "Wikiful", root_path, :class => "brand" %>
				
			
			
				<div class='session-controls'>
					<% if current_user %>
					<%= link_to "Log Out", logout_path, :class => 'btn btn-primary btn-small' %>
					Logged in as <%= current_user.email %>
					<% else %>
					<div class="btn-group">
					    <%= link_to "Articles", articles_path, :class => 'btn btn-primary btn-small'  %>
				        <%= link_to "Categories", categories_path, :class => 'btn btn-primary btn-small'  %>
						<%= link_to "Sign Up", signup_path, :class => "btn btn-small btn-primary" %>
						<%= link_to "Log In", login_path, :class => "btn btn-small btn-primary" %>
					</div>
					<% end %>
				</div>
				
				
			</div>
			
		</div>
		
	</div>

	<div class= "container">
		<div class="row">
			<div class="span4">
				<% flash.each do |name, msg| %>
				<%= content_tag :div, msg, id: "flash_#{name}" %>
				<% end %>
				
			</div>
			
		</div>
		
		<div class= "row">
		
			<div class="span9"><%= yield %> </div>
    			<div class="panel panel-primary col-xs-6 col-sm-3">
    				<div class="panel-heading">
    					<h4 class="panel-title">My Wikiful</h4>
    					</div>
    					<div class="panel-body">
    					<ul class="list-unstyled">
    						<li="list-unstyled"><%= link_to "Write a Wiki", new_article_path %></li>
    					</ul>
    					</div>
    				</div>
    				<div class="panel-heading">
    					<h4 class="panel-title">Categories</h4>
    					</div>
    					<div class="panel-body">
    					<ul class="list-unstyled">
    						<% @categories.each do |category| %>
    
    						<li><%= link_to category.name, category %></li>
    						<% end -%>
    					</ul>
    					</div>
    				
    				</div>
    				
    				<div class="panel-body">
    					<h4 class="panel-title">About Wikiful</h4>
    					<p> wlkhefksjdfkjs ajkhfdshfjk ajshfkjshf haskfhshafh ajskfhjksahf</p>
    				</div>
				</div>	
			
				
			</div>
			
		</div>
		
	</div>


</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikiful- What Do You Want To Learn Today?</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
</head>
<body>

	<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "Wikiful", root_path, :class => "brand" %>
				<%= link_to "Articles", articles_path, :class => 'btn btn-primary btn-small'  %>
				<%= link_to "Categories", categories_path, :class => 'btn btn-primary btn-small'  %>
				
			
			
				<div class='session-controls'>
					<% if current_user %>
					<%= link_to "Log Out", logout_path, :class => 'btn btn-primary btn-small' %>
					Logged in as <%= current_user.email %>
					<% else %>
					<div class="btn-group pull-right">
					    
						<%= link_to "Sign Up", signup_path, :class => "btn btn-small btn-primary" %>
						<%= link_to "Log In", login_path, :class => "btn btn-small btn-primary" %>
					</div>
					<% end %>
				</div>
				
				
			</div>
			
		</div>
		
	</div>

	<div><%= yield %> </div>
    		
    				
			
				
	
			
	
		


</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>

	<div class="error_message">
		<h2>Form is Invalid</h2>

		<ul>
			<% @user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
		
	</div>
<% end %>

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :password %>
		<%= f.text_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %>
		<%= f.text_field :password_confirmation %>
	</div>
	
	<div class="actions"><%= f.submit %></div>
<% end %>

app/views/welcome/index.html.erb
	<style type="text/css">
		body {
			margin:0;
			padding:0;
		}
		ul{
			margin:0;
			padding: 0;
		}
		ul li{
			list-style: none;
			overflow: hidden;
			height: 652px;
			position: relative;
		}
		.parallax-background {
			height:652px;
		
		}
		.architecture {
			background-image:url(https://dl.dropboxusercontent.com/u/83407479/architecture.png);
			background-size: cover; 

		}
		.chemistry {
			background-image:url(https://dl.dropboxusercontent.com/u/83407479/chemistry.png);
			background-size: cover;

		}
		.history {
			background-image:url(https://dl.dropboxusercontent.com/u/83407479/history.png);
			background-size: cover;

		}
		.liteature {
			background-image:url(https://dl.dropboxusercontent.com/u/83407479/liteature.png);
			background-size: cover;
		}

		.physics {
			background-image:url(https://dl.dropboxusercontent.com/u/83407479/physics.png);
			background-size: cover;

		}
		ul li .subcontent {

			position: absolute;
			top: 100px;
			left:100px;
			color: white;
			font-family:helvetica;

		}

		h1{
			font-size: 70px;
			margin-bottom: 0px;
		}
		
	</style>
	
		
	

	<ul class="parallax">
		<li>
			<div class="parallax-background architecture"></div>
			<div class="subcontent">
				<h1> ARCHITECTURE</h1>
			</div>
		</li>
		<li>
			<div class="parallax-background chemistry"></div>
			<div class="subcontent">
				<h1> CHEMISTRY</h1>
			</div>
		</li>
		<li>
			<div class="parallax-background history"></div>
			<div class="subcontent">
				<h1> HISTORY</h1>
			</div>
		</li>
		<li>
			<div class="parallax-background liteature"></div>
			<div class="subcontent">
				<h1> LITERATURE</h1>
			</div>
		</li>
		<li>
			<div class="parallax-background physics"></div>
			<div class="subcontent">
				<h1> PHYSICS</h1>
			</div>
		</li>
	</ul>